# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_stat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='defocusData',
            field=models.TextField(default='aaa'),
            preserve_default=False,
        ),
    ]
