# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_stat', '0002_statistics_defocusdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='alignmentShiftX',
            field=models.TextField(default='-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='alignmentShiftY',
            field=models.TextField(default='-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='astigmaticData',
            field=models.TextField(default='-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='averageAstigmatism',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='statistics',
            name='gainData',
            field=models.TextField(default='-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='numberFractionsPerMovie',
            field=models.IntegerField(default=-1),
        ),
    ]
