# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(default='qq', max_length=128),
            preserve_default=False,
        ),
    ]
