# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_proj', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='short descriptive name of this product', max_length=60, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('acquisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='create_proj.Acquisition')),
                ('ordered_by', models.ForeignKey(blank=True, help_text='user who sent this order out', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ordered by')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Concept')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.Invoice')),
            ],
        ),
    ]
