# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 19:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='short descriptive name of this product', max_length=60, unique=True)),
                ('unit_price_cnb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price_csic', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price_universidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price_empresa', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('csic', 'csic'), ('cnb', 'cnb'), ('empresa', 'empresa'), ('universidad', 'universidad')], default='cnb', max_length=11)),
                ('concept', models.CharField(choices=[('notificaci\xf3n', 'notificacion'), ('cargo', 'cargo'), ('presupuesto', 'presupuesto')], default='cargo', max_length=11)),
                ('ordered_by', models.ForeignKey(blank=True, help_text='user who sent this order out', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ordered by')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Concept')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.Invoice')),
            ],
        ),
    ]
