# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition2',
            old_name='dose_per_fraction',
            new_name='dose_rate',
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='total_dose_per_movie',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='o1',
            field=models.IntegerField(choices=[(0, '--'), (30, '30'), (70, '70'), (100, '100')], default=70),
        ),
    ]
