# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0002_acquisition_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition',
            old_name='closed',
            new_name='noScipionProject',
        ),
    ]
