# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0016_auto_20171019_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition2',
            name='acquisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_proj.Acquisition', unique=True),
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='autofocus_distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='nominal_defocus',
            field=models.CharField(default='array of floats', max_length=128),
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='nominal_magnification',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='spotsize',
            field=models.FloatField(),
        ),
    ]
