# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0018_acquisition_multiple_backup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition2',
            old_name='nominal_defocus',
            new_name='nominal_defocus_range',
        ),
        migrations.RemoveField(
            model_name='acquisition2',
            name='dose_per_frame',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='shiftLength',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='microscope',
            name='model',
            field=models.CharField(default='kk', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
