# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0019_auto_20171029_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition2',
            old_name='dose_rate',
            new_name='dose_per_fraction',
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='acquisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='create_proj.Acquisition'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
